// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  angular.module('ParsePartyApp.services').factory('parseCodeMirror', function(Counter, jsBridge) {
    var parseCodeMirror;
    parseCodeMirror = function(cm, range, callback) {
      var c, index, maxEdge, pos, token, tsl;
      c = new Counter({
        i: range.location + 1,
        end: range.length > 0 ? range.maxEdge() + 1 : range.maxEdge() + 2
      });
      while (c.i < c.end) {
        pos = cm.doc.posFromIndex(c.i);
        token = cm.getTokenAt(pos, {
          precise: true
        });
        tsl = token.string.length;
        index = cm.doc.indexFromPos({
          line: pos.line,
          ch: token.start
        });
        maxEdge = index + tsl;
        callback(pos, token);
        c.incrimentSafelyTo(maxEdge + 1);
      }
    };
    return parseCodeMirror;
  });

}).call(this);
