// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  angular.module('myApp', ['ngRoute', 'myApp.filters', 'myApp.services', 'myApp.directives', 'myApp.controllers']).config([
    '$routeProvider', 'routes', function($routeProvider, routes) {
      $routeProvider.when('/', {
        template: '<div code-mirror="5" style="width: 100%; height: 100%;"></div>',
        controller: 'MyCtrl1',
        resolve: {
          jsBridge: [
            'jsBridge', function(jsBridge) {
              return jsBridge;
            }
          ]
        }
      });
    }
  ]);

}).call(this);
