// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  angular.module('myApp.directives', []).directive('appVersion', [
    'version', function(version) {
      return function(scope, elm, attrs) {
        elm.text(version);
      };
    }
  ]).directive('codeMirror', [
    'cm1', 'jsBridge', function(cm1, jsBridge) {
      return function(scope, el, attrs) {
        var cm, d, e;
        d = cm1.deferred;
        el.css({
          'width': '100%',
          'height': '100%'
        });
        try {
          cm = CM(el[0], {
            lineNumbers: true,
            autofocus: true,
            autoCloseBrackets: true
          });
          $('.CodeMirror').css({
            'width': '100%',
            'height': '100%'
          });
        } catch (_error) {
          e = _error;
          console.log(String(e));
        }
        d.resolve(cm);
      };
    }
  ]);

}).call(this);
