// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  angular.module('myApp.directives', []).directive('appVersion', [
    'version', function(version) {
      return function(scope, elm, attrs) {
        elm.text(version);
      };
    }
  ]).directive('codeMirror', [
    'CMdi', 'CM', 'jsBridge', function(CMdi, CM, jsBridge) {
      return function(scope, elm, attrs) {
        var d, e, myCM;
        console.log('hi');
        d = CMdi;
        console.log('hii ' + String(CM));
        elm.css({
          'width': '100%',
          'height': '100%'
        });
        try {
          myCM = CM(elm[0], {
            lineNumbers: true,
            autofocus: true,
            autoCloseBrackets: true
          });
        } catch (_error) {
          e = _error;
          console.log('error CM ' + String(e));
        }
        $('.CodeMirror').css({
          'width': '100%',
          'height': '100%'
        });
        d.resolve(myCM);
        scope.apply();
      };
    }
  ]);

}).call(this);
