// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  var ngAttributedStringe,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  angular.module('myApp.services').service('attributedContent', ngAttributedStringe = (function(_super) {
    __extends(ngAttributedStringe, _super);

    function ngAttributedStringe() {
      this.string = '';
      this.attributedRanges = [];
    }

    return ngAttributedStringe;

  })(NSAttributedString));

}).call(this);
