// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  angular.module('myApp.services', []).factory('jsBridge', [
    '$q', function($q) {
      var deferred, onBridgeReady;
      deferred = $q.defer();
      onBridgeReady = function(event) {
        var bridge;
        bridge = event.bridge;
        bridge.init();
        return deferred.resolve(bridge);
      };
      document.addEventListener('WebViewJavascriptBridgeReady', onBridgeReady, false);
      return deferred.promise;
    }
  ]).factory('CMdi', [
    '$q', function($q) {
      return $q.defer();
    }
  ]).factory('CMi', [
    'CMdi', function(CMdi) {
      return CMdi.promise;
    }
  ]).factory('CM', [
    function() {
      return CodeMirror;
    }
  ]);

}).call(this);
