// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  module.exports = function(grunt) {
    require("load-grunt-tasks")(grunt);
    require("time-grunt")(grunt);
    grunt.initConfig({
      yeoman: {
        app: require("./bower.json").appPath || "app",
        dist: "dist"
      },
      watch: {
        coffee: {
          files: ["<%= yeoman.app %>/scripts/{,*/}*.coffee"],
          tasks: ["coffee:dist"]
        },
        styles: {
          files: ["<%= yeoman.app %>/styles/{,*/}*.css"],
          tasks: ["copy:styles", "autoprefixer"]
        }
      },
      autoprefixer: {
        options: ["last 1 version"],
        dist: {
          files: [
            {
              expand: true,
              cwd: "<%= yeoman.dist %>/styles",
              src: "{,*/}*.css",
              dest: "<%= yeoman.dist %>/styles"
            }
          ]
        }
      },
      clean: {
        dist: {
          files: [
            {
              dot: true,
              src: [".tmp", "<%= yeoman.dist %>/*", "!<%= yeoman.dist %>/.git*"]
            }
          ]
        },
        indent: {
          files: [
            {
              dot: true,
              src: ["<%= yeoman.app %>/scripts/{,*/}*.js"]
            }
          ]
        }
      },
      coffee: {
        dist: {
          options: {
            sourceMap: true,
            sourceRoot: ""
          },
          files: [
            {
              expand: true,
              cwd: "<%= yeoman.app %>/scripts",
              src: "{,*/}*.coffee",
              dest: "<%= yeoman.dist %>/scripts",
              ext: ".js"
            }
          ]
        },
        indent: {
          options: {
            bare: true
          },
          files: [
            {
              expand: true,
              cwd: "<%= yeoman.app %>/scripts",
              src: "{,*/}*.coffee",
              dest: "<%= yeoman.app %>/scripts",
              ext: ".js"
            }
          ]
        }
      },
      copy: {
        other: {
          files: [
            {
              expand: true,
              dot: true,
              cwd: "<%= yeoman.app %>",
              dest: "<%= yeoman.dist %>",
              src: ["*.{ico,png,txt}", ".htaccess", "bower_components/**/*", "images/{,*/}*.{gif,webp}", "fonts/*"]
            }
          ]
        },
        styles: {
          expand: true,
          cwd: "<%= yeoman.app %>/styles",
          dest: "<%= yeoman.dist %>/styles",
          src: "{,*/}*.css"
        }
      },
      concurrent: {
        dist1: ["coffee:dist", "copy:styles", "copy:other"],
        dist2: ["ngmin", "autoprefixer"]
      },
      ngmin: {
        dist: {
          files: [
            {
              expand: true,
              cwd: "<%= yeoman.dist %>/scripts",
              src: "{,*/}*.js",
              dest: "<%= yeoman.dist %>/scripts"
            }
          ]
        }
      },
      js2coffee: {
        each: {
          options: {
            single_quotes: true,
            indent: "\t"
          },
          files: [
            {
              expand: true,
              cwd: "<%= yeoman.app %>/scripts",
              src: "{,*/}*.js",
              dest: "<%= yeoman.app %>/scripts",
              ext: '.coffee'
            }
          ]
        }
      }
    });
    grunt.registerTask("indent", ["coffee:indent", "js2coffee", "clean:indent"]);
    grunt.registerTask("build", ["clean:dist", "concurrent:dist1", "concurrent:dist2"]);
    return grunt.registerTask("default", ["build"]);
  };

}).call(this);
